name: cd

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGION: us-central1
  AR_REPO: app
  SERVICE: challenge

jobs:
  cd:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Auth to Google Cloud (WIF)
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_DEPLOYER_SA }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure docker auth
      run: gcloud auth configure-docker europe-west1-docker.pkg.dev -q

    - name: Build & push image
      run: |
        IMAGE="europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/app-farmatodo/challenge:${{ github.sha }}"
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV
        docker build -t "$IMAGE" .
        docker push "$IMAGE"

    - name: Trivy scan (block on HIGH/CRITICAL)
      uses: aquasecurity/trivy-action@0.24.0
      with:
        image-ref: ${{ env.IMAGE }}
        severity: 'CRITICAL,HIGH'
        exit-code: '1'
        ignore-unfixed: true

    - name: Deploy Cloud Run
      run: |
        gcloud run deploy challenge           --image=${{ env.IMAGE }}           --region=europe-west1           --allow-unauthenticated=false           --add-cloudsql-instances="${{ secrets.CLOUDSQL_CONN }}"           --set-env-vars=SPRING_PROFILES_ACTIVE=prod,DB_NAME=challenge,DB_USER=appuser,INSTANCE_CONNECTION_NAME="${{ secrets.CLOUDSQL_CONN }}"           --set-secrets=DB_PASS=db-pass:latest
