version: '3.8'
services:
  app:
    build: .
    container_name: farmatodo-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/farmatodo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
  mailhog:
    image: mailhog/mailhog
    ports: ["1025:1025", "8025:8025"]

  db:
    image: postgres:14
    container_name: farmatodo-db
    environment:
      POSTGRES_DB: farmatodo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: