name: ci

on:
  pull_request:
  push:
    branches: [ "feature/**", "bugfix/**" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Build & test
      run: mvn -B -ntp clean verify

    - name: Upload JaCoCo report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: target/site/jacoco/**

    - name: OWASP Dependency-Check (SCA)
      uses: dependency-check/Dependency-Check_Action@main
      with:
        format: 'HTML,JSON'
        out: 'reports/dependency-check'
      continue-on-error: false

    - name: Upload SCA report
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check
        path: reports/dependency-check/**
