name: ct-nightly

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  ct:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Full verify (with integration profile if present)
      run: mvn -B -ntp clean verify -Pintegration

    - name: OWASP Dependency-Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        format: 'HTML,JSON'
        out: 'reports/dependency-check'

    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: nightly-reports
        path: |
          target/site/jacoco/**
          reports/dependency-check/**
